[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements-api.txt"]

[phases.build]
cmds = ["mkdir -p /app/data"]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
