[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 200
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
DATA_DIR = "/app/data"
QDRANT_COLLECTION = "ml-docs-copilot"
SQLITE_DB = "bm25.db"
EMBEDDING_MODEL = "nomic-ai/nomic-embed-text-v1"
CHUNK_SIZE = "500"
CHUNK_OVERLAP = "50"
TOP_K_VECTOR = "10"
TOP_K_KEYWORD = "10"
RRF_K = "60"
